<?php

namespace Tests;

use ByJG\WordNumber\EnglishWordNumber;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

class EnglishWordNumberTest extends TestCase
{
    /**
     * @return (float|int|string)[][]
     *
     * @psalm-return list{list{0, 'zero dollars'}, list{1, 'one dollar'}, list{2, 'two dollars'}, list{3, 'three dollars'}, list{4, 'four dollars'}, list{5, 'five dollars'}, list{6, 'six dollars'}, list{7, 'seven dollars'}, list{8, 'eight dollars'}, list{9, 'nine dollars'}, list{10, 'ten dollars'}, list{11, 'eleven dollars'}, list{12, 'twelve dollars'}, list{13, 'thirteen dollars'}, list{14, 'fourteen dollars'}, list{15, 'fifteen dollars'}, list{16, 'sixteen dollars'}, list{17, 'seventeen dollars'}, list{18, 'eighteen dollars'}, list{19, 'nineteen dollars'}, list{20, 'twenty dollars'}, list{21, 'twenty one dollars'}, list{22, 'twenty two dollars'}, list{23, 'twenty three dollars'}, list{24, 'twenty four dollars'}, list{25, 'twenty five dollars'}, list{26, 'twenty six dollars'}, list{27, 'twenty seven dollars'}, list{28, 'twenty eight dollars'}, list{29, 'twenty nine dollars'}, list{30, 'thirty dollars'}, list{31, 'thirty one dollars'}, list{32, 'thirty two dollars'}, list{33, 'thirty three dollars'}, list{34, 'thirty four dollars'}, list{35, 'thirty five dollars'}, list{36, 'thirty six dollars'}, list{37, 'thirty seven dollars'}, list{38, 'thirty eight dollars'}, list{39, 'thirty nine dollars'}, list{40, 'fourty dollars'}, list{41, 'fourty one dollars'}, list{42, 'fourty two dollars'}, list{43, 'fourty three dollars'}, list{44, 'fourty four dollars'}, list{45, 'fourty five dollars'}, list{46, 'fourty six dollars'}, list{47, 'fourty seven dollars'}, list{48, 'fourty eight dollars'}, list{49, 'fourty nine dollars'}, list{50, 'fifty dollars'}, list{51, 'fifty one dollars'}, list{52, 'fifty two dollars'}, list{53, 'fifty three dollars'}, list{54, 'fifty four dollars'}, list{55, 'fifty five dollars'}, list{56, 'fifty six dollars'}, list{57, 'fifty seven dollars'}, list{58, 'fifty eight dollars'}, list{59, 'fifty nine dollars'}, list{60, 'sixty dollars'}, list{61, 'sixty one dollars'}, list{62, 'sixty two dollars'}, list{63, 'sixty three dollars'}, list{64, 'sixty four dollars'}, list{65, 'sixty five dollars'}, list{66, 'sixty six dollars'}, list{67, 'sixty seven dollars'}, list{68, 'sixty eight dollars'}, list{69, 'sixty nine dollars'}, list{70, 'seventy dollars'}, list{71, 'seventy one dollars'}, list{72, 'seventy two dollars'}, list{73, 'seventy three dollars'}, list{74, 'seventy four dollars'}, list{75, 'seventy five dollars'}, list{76, 'seventy six dollars'}, list{77, 'seventy seven dollars'}, list{78, 'seventy eight dollars'}, list{79, 'seventy nine dollars'}, list{80, 'eigthty dollars'}, list{81, 'eigthty one dollars'}, list{82, 'eigthty two dollars'}, list{83, 'eigthty three dollars'}, list{84, 'eigthty four dollars'}, list{85, 'eigthty five dollars'}, list{86, 'eigthty six dollars'}, list{87, 'eigthty seven dollars'}, list{88, 'eigthty eight dollars'}, list{89, 'eigthty nine dollars'}, list{90, 'ninety dollars'}, list{91, 'ninety one dollars'}, list{92, 'ninety two dollars'}, list{93, 'ninety three dollars'}, list{94, 'ninety four dollars'}, list{95, 'ninety five dollars'}, list{96, 'ninety six dollars'}, list{97, 'ninety seven dollars'}, list{98, 'ninety eight dollars'}, list{99, 'ninety nine dollars'}, list{100, 'one hundred dollars'},...}
     */
    public static function provider(): array
    {
        return
        [
            [0, 'zero dollars'],
            [1, 'one dollar'],
            [2, 'two dollars'],
            [3, 'three dollars'],
            [4, 'four dollars'],
            [5, 'five dollars'],
            [6, 'six dollars'],
            [7, 'seven dollars'],
            [8, 'eight dollars'],
            [9, 'nine dollars'],
            [10, 'ten dollars'],
            [11, 'eleven dollars'],
            [12, 'twelve dollars'],
            [13, 'thirteen dollars'],
            [14, 'fourteen dollars'],
            [15, 'fifteen dollars'],
            [16, 'sixteen dollars'],
            [17, 'seventeen dollars'],
            [18, 'eighteen dollars'],
            [19, 'nineteen dollars'],
            [20, 'twenty dollars'],
            [21, 'twenty one dollars'],
            [22, 'twenty two dollars'],
            [23, 'twenty three dollars'],
            [24, 'twenty four dollars'],
            [25, 'twenty five dollars'],
            [26, 'twenty six dollars'],
            [27, 'twenty seven dollars'],
            [28, 'twenty eight dollars'],
            [29, 'twenty nine dollars'],
            [30, 'thirty dollars'],
            [31, 'thirty one dollars'],
            [32, 'thirty two dollars'],
            [33, 'thirty three dollars'],
            [34, 'thirty four dollars'],
            [35, 'thirty five dollars'],
            [36, 'thirty six dollars'],
            [37, 'thirty seven dollars'],
            [38, 'thirty eight dollars'],
            [39, 'thirty nine dollars'],
            [40, 'fourty dollars'],
            [41, 'fourty one dollars'],
            [42, 'fourty two dollars'],
            [43, 'fourty three dollars'],
            [44, 'fourty four dollars'],
            [45, 'fourty five dollars'],
            [46, 'fourty six dollars'],
            [47, 'fourty seven dollars'],
            [48, 'fourty eight dollars'],
            [49, 'fourty nine dollars'],
            [50, 'fifty dollars'],
            [51, 'fifty one dollars'],
            [52, 'fifty two dollars'],
            [53, 'fifty three dollars'],
            [54, 'fifty four dollars'],
            [55, 'fifty five dollars'],
            [56, 'fifty six dollars'],
            [57, 'fifty seven dollars'],
            [58, 'fifty eight dollars'],
            [59, 'fifty nine dollars'],
            [60, 'sixty dollars'],
            [61, 'sixty one dollars'],
            [62, 'sixty two dollars'],
            [63, 'sixty three dollars'],
            [64, 'sixty four dollars'],
            [65, 'sixty five dollars'],
            [66, 'sixty six dollars'],
            [67, 'sixty seven dollars'],
            [68, 'sixty eight dollars'],
            [69, 'sixty nine dollars'],
            [70, 'seventy dollars'],
            [71, 'seventy one dollars'],
            [72, 'seventy two dollars'],
            [73, 'seventy three dollars'],
            [74, 'seventy four dollars'],
            [75, 'seventy five dollars'],
            [76, 'seventy six dollars'],
            [77, 'seventy seven dollars'],
            [78, 'seventy eight dollars'],
            [79, 'seventy nine dollars'],
            [80, 'eigthty dollars'],
            [81, 'eigthty one dollars'],
            [82, 'eigthty two dollars'],
            [83, 'eigthty three dollars'],
            [84, 'eigthty four dollars'],
            [85, 'eigthty five dollars'],
            [86, 'eigthty six dollars'],
            [87, 'eigthty seven dollars'],
            [88, 'eigthty eight dollars'],
            [89, 'eigthty nine dollars'],
            [90, 'ninety dollars'],
            [91, 'ninety one dollars'],
            [92, 'ninety two dollars'],
            [93, 'ninety three dollars'],
            [94, 'ninety four dollars'],
            [95, 'ninety five dollars'],
            [96, 'ninety six dollars'],
            [97, 'ninety seven dollars'],
            [98, 'ninety eight dollars'],
            [99, 'ninety nine dollars'],
            [100, 'one hundred dollars'],
            [101, 'one hundred and one dollars'],
            [201, 'two hundred and one dollars'],
            [301, 'three hundred and one dollars'],
            [401, 'four hundred and one dollars'],
            [501, 'five hundred and one dollars'],
            [601, 'six hundred and one dollars'],
            [701, 'seven hundred and one dollars'],
            [801, 'eigth hundred and one dollars'],
            [901, 'nine hundred and one dollars'],
            [1001, 'one thousand and one dollars'],
            [1111, 'one thousand and one hundred and eleven dollars'],
            [2111, 'two thousands and one hundred and eleven dollars'],
            [3111, 'three thousands and one hundred and eleven dollars'],
            [4111, 'four thousands and one hundred and eleven dollars'],
            [5111, 'five thousands and one hundred and eleven dollars'],
            [6111, 'six thousands and one hundred and eleven dollars'],
            [7111, 'seven thousands and one hundred and eleven dollars'],
            [8111, 'eight thousands and one hundred and eleven dollars'],
            [9111, 'nine thousands and one hundred and eleven dollars'],
            [10111, 'ten thousands and one hundred and eleven dollars'],
            [11111, 'eleven thousands and one hundred and eleven dollars'],
            [1, 'one dollar'],
            [1.01, 'one dollar and one cent'],
            [1.02, 'one dollar and two cents'],
            [1.03, 'one dollar and three cents'],
            [1.04, 'one dollar and four cents'],
            [1.05, 'one dollar and five cents'],
            [1.06, 'one dollar and six cents'],
            [1.07, 'one dollar and seven cents'],
            [1.08, 'one dollar and eight cents'],
            [1.09, 'one dollar and nine cents'],
            [1.1, 'one dollar and ten cents'],
            [1.11, 'one dollar and eleven cents'],
            [1.12, 'one dollar and twelve cents'],
            [1.13, 'one dollar and thirteen cents'],
            [1.14, 'one dollar and fourteen cents'],
            [1.15, 'one dollar and fifteen cents'],
            [1.16, 'one dollar and sixteen cents'],
            [1.17, 'one dollar and seventeen cents'],
            [1.18, 'one dollar and eighteen cents'],
            [1.19, 'one dollar and nineteen cents'],
            [1.2, 'one dollar and twenty cents'],
            [1.21, 'one dollar and twenty one cents'],
            [1.22, 'one dollar and twenty two cents'],
            [1.23, 'one dollar and twenty three cents'],
            [1.24, 'one dollar and twenty four cents'],
            [1.25, 'one dollar and twenty five cents'],
            [1.26, 'one dollar and twenty six cents'],
            [1.27, 'one dollar and twenty seven cents'],
            [1.28, 'one dollar and twenty eight cents'],
            [1.29, 'one dollar and twenty nine cents'],
            [1.3, 'one dollar and thirty cents'],
            [1.31, 'one dollar and thirty one cents'],
            [1.32, 'one dollar and thirty two cents'],
            [1.33, 'one dollar and thirty three cents'],
            [1.34, 'one dollar and thirty four cents'],
            [1.35, 'one dollar and thirty five cents'],
            [1.36, 'one dollar and thirty six cents'],
            [1.37, 'one dollar and thirty seven cents'],
            [1.38, 'one dollar and thirty eight cents'],
            [1.39, 'one dollar and thirty nine cents'],
            [1.4, 'one dollar and fourty cents'],
            [1.41, 'one dollar and fourty one cents'],
            [1.42, 'one dollar and fourty two cents'],
            [1.43, 'one dollar and fourty three cents'],
            [1.44, 'one dollar and fourty four cents'],
            [1.45, 'one dollar and fourty five cents'],
            [1.46, 'one dollar and fourty six cents'],
            [1.47, 'one dollar and fourty seven cents'],
            [1.48, 'one dollar and fourty eight cents'],
            [1.49, 'one dollar and fourty nine cents'],
            [1.5, 'one dollar and fifty cents'],
            [1.51, 'one dollar and fifty one cents'],
            [1.52, 'one dollar and fifty two cents'],
            [1.53, 'one dollar and fifty three cents'],
            [1.54, 'one dollar and fifty four cents'],
            [1.55, 'one dollar and fifty five cents'],
            [1.56, 'one dollar and fifty six cents'],
            [1.57, 'one dollar and fifty seven cents'],
            [1.58, 'one dollar and fifty eight cents'],
            [1.59, 'one dollar and fifty nine cents'],
            [1.6, 'one dollar and sixty cents'],
            [1.61, 'one dollar and sixty one cents'],
            [1.62, 'one dollar and sixty two cents'],
            [1.63, 'one dollar and sixty three cents'],
            [1.64, 'one dollar and sixty four cents'],
            [1.65, 'one dollar and sixty five cents'],
            [1.66, 'one dollar and sixty six cents'],
            [1.67, 'one dollar and sixty seven cents'],
            [1.68, 'one dollar and sixty eight cents'],
            [1.69, 'one dollar and sixty nine cents'],
            [1.7, 'one dollar and seventy cents'],
            [1.71, 'one dollar and seventy one cents'],
            [1.72, 'one dollar and seventy two cents'],
            [1.73, 'one dollar and seventy three cents'],
            [1.74, 'one dollar and seventy four cents'],
            [1.75, 'one dollar and seventy five cents'],
            [1.76, 'one dollar and seventy six cents'],
            [1.77, 'one dollar and seventy seven cents'],
            [1.78, 'one dollar and seventy eight cents'],
            [1.79, 'one dollar and seventy nine cents'],
            [1.8, 'one dollar and eigthty cents'],
            [1.81, 'one dollar and eigthty one cents'],
            [1.82, 'one dollar and eigthty two cents'],
            [1.83, 'one dollar and eigthty three cents'],
            [1.84, 'one dollar and eigthty four cents'],
            [1.85, 'one dollar and eigthty five cents'],
            [1.86, 'one dollar and eigthty six cents'],
            [1.87, 'one dollar and eigthty seven cents'],
            [1.88, 'one dollar and eigthty eight cents'],
            [1.89, 'one dollar and eigthty nine cents'],
            [1.9, 'one dollar and ninety cents'],
            [1.91, 'one dollar and ninety one cents'],
            [1.92, 'one dollar and ninety two cents'],
            [1.93, 'one dollar and ninety three cents'],
            [1.94, 'one dollar and ninety four cents'],
            [1.95, 'one dollar and ninety five cents'],
            [1.96, 'one dollar and ninety six cents'],
            [1.97, 'one dollar and ninety seven cents'],
            [1.98, 'one dollar and ninety eight cents'],
            [1.99, 'one dollar and ninety nine cents'],
        ];
    }

    #[DataProvider('provider')]
    public function testEnglishWords($input, $expected): void
    {
        $englishWords = new EnglishWordNumber();
        $this->assertEquals($expected, $englishWords->write($input));
    }
}
