<?php

namespace Tests;

use ByJG\WordNumber\ItalianWordNumber;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

class ItalianWordNumberTest extends TestCase
{
    /**
     * @return (float|int|string)[][]
     *
     * @psalm-return list{list{0, 'zero euro'}, list{1, 'uno euro'}, list{2, 'due euro'}, list{3, 'tre euro'}, list{4, 'quattro euro'}, list{5, 'cinque euro'}, list{6, 'sei euro'}, list{7, 'sette euro'}, list{8, 'otto euro'}, list{9, 'nove euro'}, list{10, 'dieci euro'}, list{11, 'undici euro'}, list{12, 'dodici euro'}, list{13, 'tredici euro'}, list{14, 'quattordici euro'}, list{15, 'quindici euro'}, list{16, 'sedici euro'}, list{17, 'diciasette euro'}, list{18, 'diciotto euro'}, list{19, 'diciannove euro'}, list{20, 'venti euro'}, list{21, 'venti uno euro'}, list{22, 'venti due euro'}, list{23, 'venti tre euro'}, list{24, 'venti quattro euro'}, list{25, 'venti cinque euro'}, list{26, 'venti sei euro'}, list{27, 'venti sette euro'}, list{28, 'venti otto euro'}, list{29, 'venti nove euro'}, list{30, 'trenta euro'}, list{31, 'trenta uno euro'}, list{32, 'trenta due euro'}, list{33, 'trenta tre euro'}, list{34, 'trenta quattro euro'}, list{35, 'trenta cinque euro'}, list{36, 'trenta sei euro'}, list{37, 'trenta sette euro'}, list{38, 'trenta otto euro'}, list{39, 'trenta nove euro'}, list{40, 'quaranta euro'}, list{41, 'quaranta uno euro'}, list{42, 'quaranta due euro'}, list{43, 'quaranta tre euro'}, list{44, 'quaranta quattro euro'}, list{45, 'quaranta cinque euro'}, list{46, 'quaranta sei euro'}, list{47, 'quaranta sette euro'}, list{48, 'quaranta otto euro'}, list{49, 'quaranta nove euro'}, list{50, 'cinquanta euro'}, list{51, 'cinquanta uno euro'}, list{52, 'cinquanta due euro'}, list{53, 'cinquanta tre euro'}, list{54, 'cinquanta quattro euro'}, list{55, 'cinquanta cinque euro'}, list{56, 'cinquanta sei euro'}, list{57, 'cinquanta sette euro'}, list{58, 'cinquanta otto euro'}, list{59, 'cinquanta nove euro'}, list{60, 'sessanta euro'}, list{61, 'sessanta uno euro'}, list{62, 'sessanta due euro'}, list{63, 'sessanta tre euro'}, list{64, 'sessanta quattro euro'}, list{65, 'sessanta cinque euro'}, list{66, 'sessanta sei euro'}, list{67, 'sessanta sette euro'}, list{68, 'sessanta otto euro'}, list{69, 'sessanta nove euro'}, list{70, 'settanta euro'}, list{71, 'settanta uno euro'}, list{72, 'settanta due euro'}, list{73, 'settanta tre euro'}, list{74, 'settanta quattro euro'}, list{75, 'settanta cinque euro'}, list{76, 'settanta sei euro'}, list{77, 'settanta sette euro'}, list{78, 'settanta otto euro'}, list{79, 'settanta nove euro'}, list{80, 'ottanta euro'}, list{81, 'ottanta uno euro'}, list{82, 'ottanta due euro'}, list{83, 'ottanta tre euro'}, list{84, 'ottanta quattro euro'}, list{85, 'ottanta cinque euro'}, list{86, 'ottanta sei euro'}, list{87, 'ottanta sette euro'}, list{88, 'ottanta otto euro'}, list{89, 'ottanta nove euro'}, list{90, 'novanta euro'}, list{91, 'novanta uno euro'}, list{92, 'novanta due euro'}, list{93, 'novanta tre euro'}, list{94, 'novanta quattro euro'}, list{95, 'novanta cinque euro'}, list{96, 'novanta sei euro'}, list{97, 'novanta sette euro'}, list{98, 'novanta otto euro'}, list{99, 'novanta nove euro'}, list{100, 'cento euro'},...}
     */
    public static function provider(): array
    {
        return
        [
            [0, 'zero euro'],
            [1, 'uno euro'],
            [2, 'due euro'],
            [3, 'tre euro'],
            [4, 'quattro euro'],
            [5, 'cinque euro'],
            [6, 'sei euro'],
            [7, 'sette euro'],
            [8, 'otto euro'],
            [9, 'nove euro'],
            [10, 'dieci euro'],
            [11, 'undici euro'],
            [12, 'dodici euro'],
            [13, 'tredici euro'],
            [14, 'quattordici euro'],
            [15, 'quindici euro'],
            [16, 'sedici euro'],
            [17, 'diciasette euro'],
            [18, 'diciotto euro'],
            [19, 'diciannove euro'],
            [20, 'venti euro'],
            [21, 'venti uno euro'],
            [22, 'venti due euro'],
            [23, 'venti tre euro'],
            [24, 'venti quattro euro'],
            [25, 'venti cinque euro'],
            [26, 'venti sei euro'],
            [27, 'venti sette euro'],
            [28, 'venti otto euro'],
            [29, 'venti nove euro'],
            [30, 'trenta euro'],
            [31, 'trenta uno euro'],
            [32, 'trenta due euro'],
            [33, 'trenta tre euro'],
            [34, 'trenta quattro euro'],
            [35, 'trenta cinque euro'],
            [36, 'trenta sei euro'],
            [37, 'trenta sette euro'],
            [38, 'trenta otto euro'],
            [39, 'trenta nove euro'],
            [40, 'quaranta euro'],
            [41, 'quaranta uno euro'],
            [42, 'quaranta due euro'],
            [43, 'quaranta tre euro'],
            [44, 'quaranta quattro euro'],
            [45, 'quaranta cinque euro'],
            [46, 'quaranta sei euro'],
            [47, 'quaranta sette euro'],
            [48, 'quaranta otto euro'],
            [49, 'quaranta nove euro'],
            [50, 'cinquanta euro'],
            [51, 'cinquanta uno euro'],
            [52, 'cinquanta due euro'],
            [53, 'cinquanta tre euro'],
            [54, 'cinquanta quattro euro'],
            [55, 'cinquanta cinque euro'],
            [56, 'cinquanta sei euro'],
            [57, 'cinquanta sette euro'],
            [58, 'cinquanta otto euro'],
            [59, 'cinquanta nove euro'],
            [60, 'sessanta euro'],
            [61, 'sessanta uno euro'],
            [62, 'sessanta due euro'],
            [63, 'sessanta tre euro'],
            [64, 'sessanta quattro euro'],
            [65, 'sessanta cinque euro'],
            [66, 'sessanta sei euro'],
            [67, 'sessanta sette euro'],
            [68, 'sessanta otto euro'],
            [69, 'sessanta nove euro'],
            [70, 'settanta euro'],
            [71, 'settanta uno euro'],
            [72, 'settanta due euro'],
            [73, 'settanta tre euro'],
            [74, 'settanta quattro euro'],
            [75, 'settanta cinque euro'],
            [76, 'settanta sei euro'],
            [77, 'settanta sette euro'],
            [78, 'settanta otto euro'],
            [79, 'settanta nove euro'],
            [80, 'ottanta euro'],
            [81, 'ottanta uno euro'],
            [82, 'ottanta due euro'],
            [83, 'ottanta tre euro'],
            [84, 'ottanta quattro euro'],
            [85, 'ottanta cinque euro'],
            [86, 'ottanta sei euro'],
            [87, 'ottanta sette euro'],
            [88, 'ottanta otto euro'],
            [89, 'ottanta nove euro'],
            [90, 'novanta euro'],
            [91, 'novanta uno euro'],
            [92, 'novanta due euro'],
            [93, 'novanta tre euro'],
            [94, 'novanta quattro euro'],
            [95, 'novanta cinque euro'],
            [96, 'novanta sei euro'],
            [97, 'novanta sette euro'],
            [98, 'novanta otto euro'],
            [99, 'novanta nove euro'],
            [100, 'cento euro'],
            [101, 'mille e uno euro'],
            [201, 'duemila e uno euro'],
            [301, 'tremila e uno euro'],
            [401, 'quattromila e uno euro'],
            [501, 'cinquemila e uno euro'],
            [601, 'seimila e uno euro'],
            [701, 'settemila e uno euro'],
            [801, 'ottomila e uno euro'],
            [901, 'novemila e uno euro'],
            [1001, 'uno mille e uno euro'],
            [1111, 'uno mille e mille e undici euro'],
            [2111, 'due mila e mille e undici euro'],
            [3111, 'tre mila e mille e undici euro'],
            [4111, 'quattro mila e mille e undici euro'],
            [5111, 'cinque mila e mille e undici euro'],
            [6111, 'sei mila e mille e undici euro'],
            [7111, 'sette mila e mille e undici euro'],
            [8111, 'otto mila e mille e undici euro'],
            [9111, 'nove mila e mille e undici euro'],
            [10111, 'dieci mila e mille e undici euro'],
            [11111, 'undici mila e mille e undici euro'],
            [1, 'uno euro'],
            [1.01, 'uno euro e uno centesimo'],
            [1.02, 'uno euro e due centesimi'],
            [1.03, 'uno euro e tre centesimi'],
            [1.04, 'uno euro e quattro centesimi'],
            [1.05, 'uno euro e cinque centesimi'],
            [1.06, 'uno euro e sei centesimi'],
            [1.07, 'uno euro e sette centesimi'],
            [1.08, 'uno euro e otto centesimi'],
            [1.09, 'uno euro e nove centesimi'],
            [1.1, 'uno euro e dieci centesimi'],
            [1.11, 'uno euro e undici centesimi'],
            [1.12, 'uno euro e dodici centesimi'],
            [1.13, 'uno euro e tredici centesimi'],
            [1.14, 'uno euro e quattordici centesimi'],
            [1.15, 'uno euro e quindici centesimi'],
            [1.16, 'uno euro e sedici centesimi'],
            [1.17, 'uno euro e diciasette centesimi'],
            [1.18, 'uno euro e diciotto centesimi'],
            [1.19, 'uno euro e diciannove centesimi'],
            [1.2, 'uno euro e venti centesimi'],
            [1.21, 'uno euro e venti uno centesimi'],
            [1.22, 'uno euro e venti due centesimi'],
            [1.23, 'uno euro e venti tre centesimi'],
            [1.24, 'uno euro e venti quattro centesimi'],
            [1.25, 'uno euro e venti cinque centesimi'],
            [1.26, 'uno euro e venti sei centesimi'],
            [1.27, 'uno euro e venti sette centesimi'],
            [1.28, 'uno euro e venti otto centesimi'],
            [1.29, 'uno euro e venti nove centesimi'],
            [1.3, 'uno euro e trenta centesimi'],
            [1.31, 'uno euro e trenta uno centesimi'],
            [1.32, 'uno euro e trenta due centesimi'],
            [1.33, 'uno euro e trenta tre centesimi'],
            [1.34, 'uno euro e trenta quattro centesimi'],
            [1.35, 'uno euro e trenta cinque centesimi'],
            [1.36, 'uno euro e trenta sei centesimi'],
            [1.37, 'uno euro e trenta sette centesimi'],
            [1.38, 'uno euro e trenta otto centesimi'],
            [1.39, 'uno euro e trenta nove centesimi'],
            [1.4, 'uno euro e quaranta centesimi'],
            [1.41, 'uno euro e quaranta uno centesimi'],
            [1.42, 'uno euro e quaranta due centesimi'],
            [1.43, 'uno euro e quaranta tre centesimi'],
            [1.44, 'uno euro e quaranta quattro centesimi'],
            [1.45, 'uno euro e quaranta cinque centesimi'],
            [1.46, 'uno euro e quaranta sei centesimi'],
            [1.47, 'uno euro e quaranta sette centesimi'],
            [1.48, 'uno euro e quaranta otto centesimi'],
            [1.49, 'uno euro e quaranta nove centesimi'],
            [1.5, 'uno euro e cinquanta centesimi'],
            [1.51, 'uno euro e cinquanta uno centesimi'],
            [1.52, 'uno euro e cinquanta due centesimi'],
            [1.53, 'uno euro e cinquanta tre centesimi'],
            [1.54, 'uno euro e cinquanta quattro centesimi'],
            [1.55, 'uno euro e cinquanta cinque centesimi'],
            [1.56, 'uno euro e cinquanta sei centesimi'],
            [1.57, 'uno euro e cinquanta sette centesimi'],
            [1.58, 'uno euro e cinquanta otto centesimi'],
            [1.59, 'uno euro e cinquanta nove centesimi'],
            [1.6, 'uno euro e sessanta centesimi'],
            [1.61, 'uno euro e sessanta uno centesimi'],
            [1.62, 'uno euro e sessanta due centesimi'],
            [1.63, 'uno euro e sessanta tre centesimi'],
            [1.64, 'uno euro e sessanta quattro centesimi'],
            [1.65, 'uno euro e sessanta cinque centesimi'],
            [1.66, 'uno euro e sessanta sei centesimi'],
            [1.67, 'uno euro e sessanta sette centesimi'],
            [1.68, 'uno euro e sessanta otto centesimi'],
            [1.69, 'uno euro e sessanta nove centesimi'],
            [1.7, 'uno euro e settanta centesimi'],
            [1.71, 'uno euro e settanta uno centesimi'],
            [1.72, 'uno euro e settanta due centesimi'],
            [1.73, 'uno euro e settanta tre centesimi'],
            [1.74, 'uno euro e settanta quattro centesimi'],
            [1.75, 'uno euro e settanta cinque centesimi'],
            [1.76, 'uno euro e settanta sei centesimi'],
            [1.77, 'uno euro e settanta sette centesimi'],
            [1.78, 'uno euro e settanta otto centesimi'],
            [1.79, 'uno euro e settanta nove centesimi'],
            [1.8, 'uno euro e ottanta centesimi'],
            [1.81, 'uno euro e ottanta uno centesimi'],
            [1.82, 'uno euro e ottanta due centesimi'],
            [1.83, 'uno euro e ottanta tre centesimi'],
            [1.84, 'uno euro e ottanta quattro centesimi'],
            [1.85, 'uno euro e ottanta cinque centesimi'],
            [1.86, 'uno euro e ottanta sei centesimi'],
            [1.87, 'uno euro e ottanta sette centesimi'],
            [1.88, 'uno euro e ottanta otto centesimi'],
            [1.89, 'uno euro e ottanta nove centesimi'],
            [1.9, 'uno euro e novanta centesimi'],
            [1.91, 'uno euro e novanta uno centesimi'],
            [1.92, 'uno euro e novanta due centesimi'],
            [1.93, 'uno euro e novanta tre centesimi'],
            [1.94, 'uno euro e novanta quattro centesimi'],
            [1.95, 'uno euro e novanta cinque centesimi'],
            [1.96, 'uno euro e novanta sei centesimi'],
            [1.97, 'uno euro e novanta sette centesimi'],
            [1.98, 'uno euro e novanta otto centesimi'],
            [1.99, 'uno euro e novanta nove centesimi'],
        ];
    }

    #[DataProvider('provider')]
    public function testItalianWords($input, $expected): void
    {
        $englishWords = new ItalianWordNumber();
        $this->assertEquals($expected, $englishWords->write($input));
    }
}
